language: python
python:
  - "3.7"

script:
  - pytest --cov=mypy_coverage_demo --cov-report xml:pytestcov.xml test
  - mypy --cobertura-xml-report coverage .

after_success:
  - bash <(curl -s https://codecov.io/bash) -f $TRAVIS_BUILD_DIR/pytestcov.xml --flag travis_tests
  - bash <(curl -s https://codecov.io/bash) -f $TRAVIS_BUILD_DIR/mypycov/cobertura.xml --flag travis_mypy
