version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: python:3.7-stretch

    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: mypy --cobertura-xml-report mypycov .
      - run: pytest --cov=mypy_coverage_demo --cov-report xml:pytestcov.xml test
      - codecov/upload:
        file: ./mypycov/cobertura.xml
      - codecov/upload:
        file: ./pytestcov.xml
