version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: python:3.7-stretch

    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: mypy --cobertura-xml-report coverage .
      - codecov/upload:
        file: ./coverage/cobertura.xml
